2023-12-31 18:10:46,625 - INFO: Connecting to 149.154.167.92:443/TcpFull...
2023-12-31 18:10:46,815 - INFO: Connection to 149.154.167.92:443/TcpFull complete!
2023-12-31 18:10:53,685 - ERROR: [!] Unexpected Error: One of the users you tried to add is already in too many channels/supergroups (caused by InviteToChannelRequest)
Traceback (most recent call last):
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/add2group.py", line 154, in <module>
    client(InviteToChannelRequest(target_group_entity, [user_to_add]))
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.UserChannelsTooMuchError: One of the users you tried to add is already in too many channels/supergroups (caused by InviteToChannelRequest)
2023-12-31 18:10:58,976 - ERROR: [!] Unexpected Error: One of the users you tried to add is already in too many channels/supergroups (caused by InviteToChannelRequest)
Traceback (most recent call last):
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/add2group.py", line 154, in <module>
    client(InviteToChannelRequest(target_group_entity, [user_to_add]))
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.UserChannelsTooMuchError: One of the users you tried to add is already in too many channels/supergroups (caused by InviteToChannelRequest)
2023-12-31 18:11:04,312 - WARNING: [!] Peer flood error.
2023-12-31 18:11:09,738 - WARNING: [!] Peer flood error.
2023-12-31 18:11:15,127 - WARNING: [!] Peer flood error.
2023-12-31 18:11:20,457 - WARNING: [!] Peer flood error.
2023-12-31 18:11:26,041 - WARNING: [!] Peer flood error.
2023-12-31 18:11:31,321 - WARNING: [!] Peer flood error.
2023-12-31 18:11:40,027 - WARNING: [!] Peer flood error.
2023-12-31 18:11:45,391 - WARNING: [!] Peer flood error.
2023-12-31 18:11:50,801 - WARNING: [!] Peer flood error.
2023-12-31 18:11:56,228 - WARNING: [!] Peer flood error.
2023-12-31 18:12:01,475 - WARNING: [!] Peer flood error.
2023-12-31 18:12:06,776 - WARNING: [!] Peer flood error.
2023-12-31 18:12:12,150 - WARNING: [!] Peer flood error.
2023-12-31 18:12:17,591 - WARNING: [!] Peer flood error.
2023-12-31 18:12:23,080 - WARNING: [!] Peer flood error.
2023-12-31 18:12:28,406 - WARNING: [!] Peer flood error.
2023-12-31 18:13:56,097 - WARNING: [!] Peer flood error.
2023-12-31 18:14:01,102 - INFO: Got difference for account updates
2023-12-31 18:14:01,496 - WARNING: [!] Peer flood error.
2023-12-31 18:14:06,724 - WARNING: [!] Peer flood error.
2023-12-31 18:14:12,049 - WARNING: [!] Peer flood error.
2023-12-31 18:14:17,293 - WARNING: [!] Peer flood error.
2023-12-31 18:14:22,628 - WARNING: [!] Peer flood error.
2023-12-31 18:14:27,842 - WARNING: [!] Peer flood error.
2023-12-31 18:14:33,106 - WARNING: [!] Peer flood error.
2023-12-31 18:14:38,351 - WARNING: [!] Peer flood error.
2023-12-31 18:14:43,570 - WARNING: [!] Peer flood error.
2023-12-31 18:14:48,908 - WARNING: [!] Peer flood error.
2023-12-31 18:14:54,287 - WARNING: [!] Peer flood error.
2023-12-31 18:14:59,527 - WARNING: [!] Peer flood error.
2023-12-31 18:15:04,952 - WARNING: [!] Peer flood error.
2023-12-31 18:15:10,175 - WARNING: [!] Peer flood error.
2023-12-31 18:15:15,397 - WARNING: [!] The user's privacy settings do not allow you to do this. Skipping.
2023-12-31 18:15:20,731 - WARNING: [!] Peer flood error.
2023-12-31 18:15:26,065 - WARNING: [!] Peer flood error.
2023-12-31 18:15:31,474 - WARNING: [!] Peer flood error.
2023-12-31 18:15:36,716 - WARNING: [!] Peer flood error.
2023-12-31 18:15:42,022 - ERROR: [!] Unexpected Error: One of the users you tried to add is already in too many channels/supergroups (caused by InviteToChannelRequest)
Traceback (most recent call last):
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/add2group.py", line 154, in <module>
    client(InviteToChannelRequest(target_group_entity, [user_to_add]))
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.UserChannelsTooMuchError: One of the users you tried to add is already in too many channels/supergroups (caused by InviteToChannelRequest)
2023-12-31 18:15:47,261 - WARNING: [!] Peer flood error.
2023-12-31 18:15:52,478 - WARNING: [!] Peer flood error.
2023-12-31 18:15:57,699 - WARNING: [!] Peer flood error.
2023-12-31 18:16:02,924 - WARNING: [!] Peer flood error.
2023-12-31 18:16:08,338 - WARNING: [!] Peer flood error.
2023-12-31 18:16:13,571 - WARNING: [!] Peer flood error.
2023-12-31 18:16:19,001 - WARNING: [!] Peer flood error.
2023-12-31 18:16:24,235 - WARNING: [!] Peer flood error.
2023-12-31 18:16:29,458 - WARNING: [!] Peer flood error.
2023-12-31 18:16:34,695 - WARNING: [!] Peer flood error.
2023-12-31 18:16:40,089 - WARNING: [!] Peer flood error.
2023-12-31 18:16:45,392 - WARNING: [!] Peer flood error.
2023-12-31 18:16:50,835 - WARNING: [!] Peer flood error.
2023-12-31 18:16:56,061 - WARNING: [!] Peer flood error.
2023-12-31 18:17:01,324 - WARNING: [!] Peer flood error.
2023-12-31 18:17:06,707 - WARNING: [!] Peer flood error.
2023-12-31 18:17:12,339 - WARNING: [!] Peer flood error.
2023-12-31 18:17:17,721 - WARNING: [!] Peer flood error.
2023-12-31 18:17:22,997 - WARNING: [!] Peer flood error.
2023-12-31 18:17:28,251 - WARNING: [!] Peer flood error.
2023-12-31 18:17:33,741 - ERROR: [!] Unexpected Error: One of the users you tried to add is already in too many channels/supergroups (caused by InviteToChannelRequest)
Traceback (most recent call last):
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/add2group.py", line 154, in <module>
    client(InviteToChannelRequest(target_group_entity, [user_to_add]))
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.UserChannelsTooMuchError: One of the users you tried to add is already in too many channels/supergroups (caused by InviteToChannelRequest)
2023-12-31 18:17:39,177 - ERROR: [!] Unexpected Error: One of the users you tried to add is already in too many channels/supergroups (caused by InviteToChannelRequest)
Traceback (most recent call last):
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/add2group.py", line 154, in <module>
    client(InviteToChannelRequest(target_group_entity, [user_to_add]))
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/emmanuel/Desktop/projects/telegram_scrapper_bot/venv/lib/python3.10/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.UserChannelsTooMuchError: One of the users you tried to add is already in too many channels/supergroups (caused by InviteToChannelRequest)
2023-12-31 18:17:44,595 - WARNING: [!] Peer flood error.
2023-12-31 18:17:49,826 - WARNING: [!] Peer flood error.
2023-12-31 18:17:55,251 - WARNING: [!] Peer flood error.
2023-12-31 18:18:00,672 - WARNING: [!] Peer flood error.
2023-12-31 18:18:06,142 - WARNING: [!] Peer flood error.
2023-12-31 18:18:11,362 - WARNING: [!] Peer flood error.
2023-12-31 18:18:16,693 - WARNING: [!] Peer flood error.
2023-12-31 18:18:21,972 - WARNING: [!] Peer flood error.
2023-12-31 18:18:27,201 - WARNING: [!] Peer flood error.
2023-12-31 18:18:32,463 - WARNING: [!] Peer flood error.
2023-12-31 18:18:37,822 - WARNING: [!] Peer flood error.
2023-12-31 18:18:43,169 - WARNING: [!] Peer flood error.
2023-12-31 18:18:48,595 - WARNING: [!] Peer flood error.
2023-12-31 18:18:53,983 - WARNING: [!] Peer flood error.
2023-12-31 18:18:59,452 - WARNING: [!] Peer flood error.
2023-12-31 18:19:04,678 - WARNING: [!] Peer flood error.
2023-12-31 18:19:09,902 - WARNING: [!] Peer flood error.
2023-12-31 18:19:15,152 - WARNING: [!] Peer flood error.
2023-12-31 18:19:20,444 - ERROR: this account has flood wait error, wait for at least 24 hours to use it again
2023-12-31 18:19:20,444 - INFO: this account has flood wait error, wait for at least 24 hours to use it again
